<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_persona extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_persona_model');
    } 

    /*
     * Listing of tipo_persona
     */
    function index()
    {
        $data['tipo_persona'] = $this->Tipo_persona_model->get_all_tipo_persona();
        
        $data['_view'] = 'tipo_persona/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tipo_persona
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nombre_tipo_persona' => $this->input->post('nombre_tipo_persona'),
            );
            
            $tipo_persona_id = $this->Tipo_persona_model->add_tipo_persona($params);
            redirect('tipo_persona/index');
        }
        else
        {            
            $data['_view'] = 'tipo_persona/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tipo_persona
     */
    function edit($id_tipo_persona)
    {   
        // check if the tipo_persona exists before trying to edit it
        $data['tipo_persona'] = $this->Tipo_persona_model->get_tipo_persona($id_tipo_persona);
        
        if(isset($data['tipo_persona']['id_tipo_persona']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nombre_tipo_persona' => $this->input->post('nombre_tipo_persona'),
                );

                $this->Tipo_persona_model->update_tipo_persona($id_tipo_persona,$params);            
                redirect('tipo_persona/index');
            }
            else
            {
                $data['_view'] = 'tipo_persona/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tipo_persona you are trying to edit does not exist.');
    } 

    /*
     * Deleting tipo_persona
     */
    function remove($id_tipo_persona)
    {
        $tipo_persona = $this->Tipo_persona_model->get_tipo_persona($id_tipo_persona);

        // check if the tipo_persona exists before trying to delete it
        if(isset($tipo_persona['id_tipo_persona']))
        {
            $this->Tipo_persona_model->delete_tipo_persona($id_tipo_persona);
            redirect('tipo_persona/index');
        }
        else
            show_error('The tipo_persona you are trying to delete does not exist.');
    }
    
}
