<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ventum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ventum_model');
        
        
        date_default_timezone_set("America/Argentina/Buenos_Aires");
    } 

    /*
     * Listing of venta
     */
    function index()
    {
        $data['venta'] = $this->Ventum_model->get_all_venta();$this->load->model('Persona_model');
            $data['all_personas'] = $this->Persona_model->get_all_personas_Clientes();

            $this->load->model('Producto_model');
            $data['all_producto'] = $this->Producto_model->get_all_producto();

        
        $data['_view'] = 'ventum/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Creo una nueva venta
     */
    function add()
    {   
        $this->load->library('form_validation');
        $this->load->model('Productos_pedido_model');
        $this->form_validation->set_rules('id_cliente_venta','Id Cliente Venta','required');        
        if($this->form_validation->run())     
        {   
            $params = array(
                'id_cliente_venta' => $this->input->post('id_cliente_venta'),
                'hora_venta' => "" . date("G:i:s") . "",
                'fecha_venta' =>  "" . date("Y-m-d") ."",
            );
            //cargo una parte de la venta y recibo el id 
            $ventum_id = $this->Ventum_model->add_ventum($params);
            //recorro el array con la cantidad de procuctos que recibi y los voy cargando en otra tabla
                    $productos = $this->input->post('id_productos_venta');
                        foreach($productos as $producto)
                            {
                                $params2 = array(
                                    'id_pedido' => $ventum_id,
                                    'id_producto' => $producto,
                                );
                                $this->Productos_pedido_model->add_productos_pedido($params2);
                            }
            redirect('ventum/index');
        }
        else
        {
            $this->load->model('Persona_model');
            $data['all_personas'] = $this->Persona_model->get_all_personas_Clientes();

            $this->load->model('Producto_model');
            $data['all_producto'] = $this->Producto_model->get_all_producto();
            
            $data['_view'] = 'ventum/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a ventum
     */
    function edit($id_venta)
    {   
        // check if the ventum exists before trying to edit it
        $data['ventum'] = $this->Ventum_model->get_ventum($id_venta);
        
        if(isset($data['ventum']['id_venta']))
        {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('id_cliente_venta','Id Cliente Venta','required');
            $this->form_validation->set_rules('id_productos_venta','Id Productos Venta','required');
        
            if($this->form_validation->run())     
            {   
                $params = array(
                    'id_cliente_venta' => $this->input->post('id_cliente_venta'),
                    'id_productos_venta' => $this->input->post('id_productos_venta'),
                    'hora_venta' => $this->input->post('hora_venta'),
                    'fecha_venta' => $this->input->post('fecha_venta'),






                );

                $this->Ventum_model->update_ventum($id_venta,$params);            
                redirect('ventum/index');
            }
            else
            {
                $this->load->model('Persona_model');
                $data['all_personas'] = $this->Persona_model->get_all_personas();

                $this->load->model('Producto_model');
                $data['all_producto'] = $this->Producto_model->get_all_producto();

                $data['_view'] = 'ventum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The ventum you are trying to edit does not exist.');
    } 

    /*
     * Deleting ventum
     */
    function remove($id_venta)
    {
        $ventum = $this->Ventum_model->get_ventum($id_venta);

        // check if the ventum exists before trying to delete it
        if(isset($ventum['id_venta']))
        {
            $this->Ventum_model->delete_ventum($id_venta);
            redirect('ventum/index');
        }
        else
            show_error('The ventum you are trying to delete does not exist.');
    }
    
}