<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ventum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ventum_model');
    } 

    /*
     * Listing of venta
     */
    function index()
    {
        $data['venta'] = $this->Ventum_model->get_all_venta();
        
        $data['_view'] = 'ventum/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new ventum
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_cliente_venta' => $this->input->post('id_cliente_venta'),
				'id_productos_venta' => $this->input->post('id_productos_venta'),
				'hora_venta' => $this->input->post('hora_venta'),
				'fecha_venta' => $this->input->post('fecha_venta'),
            );
            
            $ventum_id = $this->Ventum_model->add_ventum($params);
            redirect('ventum/index');
        }
        else
        {            
            $data['_view'] = 'ventum/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a ventum
     */
    function edit($id_venta)
    {   
        // check if the ventum exists before trying to edit it
        $data['ventum'] = $this->Ventum_model->get_ventum($id_venta);
        
        if(isset($data['ventum']['id_venta']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_cliente_venta' => $this->input->post('id_cliente_venta'),
					'id_productos_venta' => $this->input->post('id_productos_venta'),
					'hora_venta' => $this->input->post('hora_venta'),
					'fecha_venta' => $this->input->post('fecha_venta'),
                );

                $this->Ventum_model->update_ventum($id_venta,$params);            
                redirect('ventum/index');
            }
            else
            {
                $data['_view'] = 'ventum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The ventum you are trying to edit does not exist.');
    } 

    /*
     * Deleting ventum
     */
    function remove($id_venta)
    {
        $ventum = $this->Ventum_model->get_ventum($id_venta);

        // check if the ventum exists before trying to delete it
        if(isset($ventum['id_venta']))
        {
            $this->Ventum_model->delete_ventum($id_venta);
            redirect('ventum/index');
        }
        else
            show_error('The ventum you are trying to delete does not exist.');
    }
    
}
