<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ventum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ventum_model');
          $this->lang->load('spanish');
        $this->load->library('ion_auth');   
        $this->load->library('validaciones');
        $this->load->library('session');
        
        date_default_timezone_set("America/Argentina/Buenos_Aires");
    } 

    /*
     * Listing of venta
     */
    function index()
    {
$user = $this->ion_auth->user()->row();
            if($this->ion_auth->loginCheck() && $this->ion_auth->RolCheck($user->id, $this->config->item('VerVentas'))){
                $data['usuario'] =$user->first_name;
                $data['id_user'] =$user->id;   

        $data['venta'] = $this->Ventum_model->get_all_venta(); 
        $this->load->view('navbar', $data);
        $this->load->view('ventum/index',$data);
}
    }

    /*
     * Creo una nueva venta
     */
    function add()
    {   
        $user = $this->ion_auth->user()->row();
            if($this->ion_auth->loginCheck() && $this->ion_auth->RolCheck($user->id, $this->config->item('NuevaVenta'))){
                $data['usuario'] =$user->first_name;
                $data['id_user'] =$user->id;   

        $this->load->library('form_validation');
        $this->load->model('Productos_pedido_model');
        $this->load->model('Producto_model');
        $this->form_validation->set_rules('id_cliente_venta','Id Cliente Venta','required');        
        if($this->form_validation->run())     
        {   
            $params = array(
                'id_cliente_venta' => $this->input->post('id_cliente_venta'),
                'hora_venta' => "" . date("G:i:s") . "",
                'fecha_venta' =>  "" . date("Y-m-d") ."",
                'id_user' => $user->id,
            );
            //cargo una parte de la venta y recibo el id 
            $ventum_id = $this->Ventum_model->add_ventum($params);
            //recorro el array con la cantidad de procuctos que recibi y los voy cargando en otra tabla
                    $productos = $this->input->post('id_productos_venta');
                    $monto=0;
                        foreach($productos as $producto)
                            {
                                //traigo el valor de cada producto y lo sumo para agregar a la venta
                                $costo = $this->Producto_model->get_productos_price($producto);
                                $monto= $monto + $costo;
                                $params2 = array(
                                    'id_pedido' => $ventum_id,
                                    'id_productos' => $producto,
                                    'costo' => $costo,
                                );
                                $this->Productos_pedido_model->add_productos_pedido($params2);
                                $this->Producto_model->update_producto_stock($producto);    
                            }

                    $this->Ventum_model->update_ventum_monto($ventum_id,$monto);        
            redirect('ventum/index');
        }
        else
        {
            $this->load->model('Persona_model');
            $data['all_personas'] = $this->Persona_model->get_all_personas_Clientes();

            $this->load->model('Producto_model');
            $data['all_producto'] = $this->Producto_model->get_all_producto();
            
                    $this->load->view('navbar', $data);
        $this->load->view('ventum/add',$data);
        }
    }  
}

    /*
     * Editing a ventum
     */
    function edit($id_venta)
    {   
        // check if the ventum exists before trying to edit it
        $data['ventum'] = $this->Ventum_model->get_ventum($id_venta);
        
        if(isset($data['ventum']['id_venta']))
        {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('id_cliente_venta','Id Cliente Venta','required');
            $this->form_validation->set_rules('id_productos_venta','Id Productos Venta','required');
        
            if($this->form_validation->run())     
            {   
                $params = array(
                    'id_cliente_venta' => $this->input->post('id_cliente_venta'),
                    'id_productos_venta' => $this->input->post('id_productos_venta'),
                    'hora_venta' => $this->input->post('hora_venta'),
                    'fecha_venta' => $this->input->post('fecha_venta'),
                );

                $this->Ventum_model->update_ventum($id_venta,$params);            
                redirect('ventum/index');
            }
            else
            {
                $this->load->model('Persona_model');
                $data['all_personas'] = $this->Persona_model->get_all_personas_Clientes();

                $this->load->model('Producto_model');
                $data['all_producto'] = $this->Producto_model->get_all_producto();

                $data['_view'] = 'ventum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The ventum you are trying to edit does not exist.');
    } 

    /*
     * Eliminio una venta
     * TODO: eliminar la relacion con productos x venta
     */
    function remove($id_venta)
    {
        $ventum = $this->Ventum_model->get_ventum($id_venta);

        // chequeo que exista la venta antes de Eliminarla
        if(isset($ventum['id_venta']))
        {
            $this->Ventum_model->delete_ventum($id_venta);
            redirect('ventum/index');
        }
        else
            show_error('The ventum you are trying to delete does not exist.');
    }
      /*
     * Ver el detalle de una venta
     */
    function view($id_venta)
    {
        $ventum = $this->Ventum_model->get_ventum($id_venta);

        // chequeo que exista la venta buscar los detalles
        if(isset($ventum['id_venta']))
        {
             $this->load->model('Productos_pedido_model');
                
             $data['ventum'] = $this->Ventum_model->get_ventum($id_venta);
             $data['producto'] = $this->Productos_pedido_model->get_productos_pedido($id_venta);
             $data['_view'] = 'ventum/view';
             $this->load->view('layouts/main',$data);
        }
        else
           //$this->session->set_flashdata('success', 'teeeeest');
            redirect('ventum/index');
    }
    
}