<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Persona_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get persona by id_persona
     */
    function get_persona($id_persona)
    {
        return $this->db->get_where('personas',array('id_persona'=>$id_persona))->row_array();
    }
        
    /*
     * Get all clientes
     */
    function get_all_personas_Clientes()
    {
        $this->db->order_by('id_persona', 'desc')
                    ->where('tipo_persona','1');
        return $this->db->get('personas')->result_array();
    }
    /*
     * Get all clientes
     */
       function get_all_personas_Proveedores()
    {
        $this->db->order_by('id_persona', 'desc')
                ->where('tipo_persona','2');
        return $this->db->get('personas')->result_array();
    }
     /*
     * Get all clientes
     */

       function get_all_personas_Empleados()
    {
        $this->db->order_by('id_persona', 'desc');
        return $this->db->get('personas')->result_array();
    }
        
    /*
     * function to add new persona
     */
    function add_persona($params)
    {
        $this->db->insert('personas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update persona
     */
    function update_persona($id_persona,$params)
    {
        $this->db->where('id_persona',$id_persona);
        return $this->db->update('personas',$params);
    }
    
    /*
     * function to delete persona
     */
    function delete_persona($id_persona)
    {
        return $this->db->delete('personas',array('id_persona'=>$id_persona));
    }
}
