<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Productos_pedido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get productos_pedido by 
     */
    function get_productos_pedido($param)
    {
        $array = array(
            'id_pedido'=>$param,
            );
        $this->db->where($array);
        return $this->db->get('productos_pedido')->result_array();
    }
        
    /*
     * Get all productos_pedido
     */
    function get_all_productos_pedido()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('productos_pedido')->result_array();
    }
        
    /*
     *  recibo array con id de venta e id de producto
     */
    function add_productos_pedido($params)
    {
        $this->db->insert('productos_pedido',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update productos_pedido
     */
    function update_productos_pedido($param,$params)
    {
        $this->db->where('',$param);
        return $this->db->update('productos_pedido',$params);
    }
    
    /*
     * function to delete productos_pedido
     */
    function delete_productos_pedido($param)
    {
        return $this->db->delete('productos_pedido',array(''=>$param));
    }
}
