<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Producto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get producto by id_producto
     */
    function get_producto($id_producto)
    {
        return $this->db->get_where('producto',array('id_producto'=>$id_producto))->row_array();
    }
        
    /*
     * Get all producto
     */
    function get_all_producto()
    {
        $this->db->order_by('id_producto', 'desc');
        return $this->db->get('producto')->result_array();
    }
        
    /*
     * function to add new producto
     */
    function add_producto($params)
    {
        $this->db->insert('producto',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update producto
     */
    function update_producto($id_producto,$params)
    {
        $this->db->where('id_producto',$id_producto);
        return $this->db->update('producto',$params);
    }
    
    /*
     * function to delete producto
     */
    function delete_producto($id_producto)
    {
        return $this->db->delete('producto',array('id_producto'=>$id_producto));
    }
}
