<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Productos_pedido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get productos_pedido by 
     */
    function get_productos_pedido($)
    {
        return $this->db->get_where('productos_pedido',array(''=>$))->row_array();
    }
        
    /*
     * Get all productos_pedido
     */
    function get_all_productos_pedido()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('productos_pedido')->result_array();
    }
        
    /*
     * function to add new productos_pedido
     */
    function add_productos_pedido($params)
    {
        $this->db->insert('productos_pedido',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update productos_pedido
     */
    function update_productos_pedido($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('productos_pedido',$params);
    }
    
    /*
     * function to delete productos_pedido
     */
    function delete_productos_pedido($)
    {
        return $this->db->delete('productos_pedido',array(''=>$));
    }
}
