<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ventum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ventum by id_venta
     */
    function get_ventum($id_venta)
    {
         $this->db->join('personas', 'id_cliente_venta = id_persona');
         $this->db->join('users', 'venta.id_user=users.id');
        return $this->db->get_where('venta',array('id_venta'=>$id_venta))->row_array();
    }
        
    /*
     * Get all venta
     */
    function get_all_venta()
    {
        $this->db->order_by('id_venta', 'desc');
           $this->db->join('personas', 'id_cliente_venta = id_persona');

        return $this->db->get('venta')->result_array();
    }
        
    /*
     * function to add new ventum
     */
    function add_ventum($params)
    {
        $this->db->insert('venta',$params);
        return $this->db->insert_id();
    }


   /*
     * actualizo el monto de la venta
     */
    function update_ventum_monto($id_venta,$params)
    {   
        $array = array(
            'monto' => $params,
            );
        $this->db->where('id_venta',$id_venta);
        return $this->db->update('venta',$array);
    }

    
    /*
     * function to update ventum
     */
    function update_ventum($id_venta,$params)
    {
        $this->db->where('id_venta',$id_venta);
        return $this->db->update('venta',$params);
    }
    
    /*
     * function to delete ventum
     */
    function delete_ventum($id_venta)
    {
        return $this->db->delete('venta',array('id_venta'=>$id_venta));
    }
}